#!/usr/bin/env python

GET_BRICK_COLOR_WAIT = 0
GET_BRICK_COLOR_RED = 1
GET_BRICK_COLOR_YELLOW = 2 
GET_BRICK_COLOR_BLUE = 3



# SERVER PARAMETERS
IP = '192.168.0.4'
PORT = 5020

REGISTER_REFRESH_FREQUENCY = 1